dist: xenial
language: python

python:
- '3.7'
- '3.8'

cache:
  directories:
  - "$HOME/.cache/pip"

install:
- make install

script:
- make check coverage

deploy:
  provider: pypi
  user: luizalabs
  distributions: sdist bdist_wheel
  password:
    secure: aLDas4t63jK3x295uqeB+2NdQnju45aMGYm7MI5IWqIEUY4KAPSQ0tybR4Lmbbg6tWjjOmd6mR5aNjkFIiyOQXiMCiwVm8TaifBEj+Q6rOu0eHOR3wpCtwX+XUIDuSjqUjk5iTzQsxBvDLpSLPsfi0IuLpa+4seXC/HjjtxJ/Kae4OorByAmuT5l5YeR1bVZTWnxmbO32Pe8/kiXxjDa7EkI0fYQeBBpeDe69tnxW3693+/uLani59ToKfbMSljSQBrstEj5KY1iZpETukUPhYE3QoRNSNQQAurCLVQqWmsnIhFBcP1Qs0+ZLiTiwQ81kR5uEpAu519vo3vvzO/pOKz4ev8fpGwdDyEhwD19Tlv0HY22gDrgcZf7OLNDpFRxBrKFqaOgReVaPm39ICbPqnkBs4i5aKPjdzEFYD8cYukq/cE6UVqkWXKSimll7OhUpMAvm9lLqTyd0dEMOAufoPb+e20+X8GCFPtjd/3qJhLDGtzo+RgyNN+1ffETvUrBT9zk9kRnsxGN3I/SwpAKy0MEulP+bL3l7NZj27Ej5cwiRrmt3JEqXSG+RnxC2DFM9b9ILv2+uFV6obaMZXv7Hnv3lpI33Z08UcXOn4pfyuzklHuhV26rU9CqBla04hTAS/osqmTRgr5G+LujuVMY0TAB+rTAZYtLItSbsih+On4=
  on:
    tags: true
    repo: luizalabs/lasier
  skip_cleanup: true
